### ISSUE TITLE
Adding project requirements in README.md

### ISSUE THREAD

**Issue by MadinaB** [mozilla/coverage-crawler#171]
Project installation raises bugs during the process which leads to incrementally updating software to fit the project needs. I think it would be useful to add required software for setting up the project in  README.md.

**Comment by marco-c** [comment]
Definitely!

**Comment by MadinaB** [comment]
@marco-c, I want to add some small set up guide and provide a Vagrantfile for easy project set up for new comers. Can I do it proposing them Linux OS?

Taken from Travis CL system_info:

Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

I want to propose Vagrantfile with Ubuntu 16.04, though. Should I?

**Comment by MadinaB** [comment]
One more software requirement is needed, when running download_artifacts.py on new machine, getting this problem:
Traceback (most recent call last):
  File "line.py", line 12, in <module>
    subprocess.call(['hg', 'clone', 'https://hg.mozilla.org/mozilla-central/', '--rev', revision])
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'hg'

Adding this lines resolved it:
     sudo add-apt-repository -y ppa:mercurial-ppa/releases
     sudo apt-get update
     sudo apt-get install -y mercurial

TODO() add to Readme.md
