### ISSUE TITLE
create git actions

### ISSUE THREAD

**Issue by nnrepos** [mozilla/coverage-crawler#558]
for now, when creating a PR, we only run taskcluster tests.
our python unittests have to be run manually.
i think we should add a git action which runs those test before we approve any PR (for example, dependabot's PRs sometimes break them).

**Comment by marco-c** [comment]
Which tests are not run on Taskcluster?

**Comment by nnrepos** [comment]
according to [this log](https://community-tc.services.mozilla.com/tasks/EZXsUEX6Q-63WVYwc7ydTw/runs/0/logs/public/logs/live_backing.log), and according to `.taskcluster.yml`, we only run the tests which follow this pattern: `tests/test_*.py`.
i think we should change the yml to `python -m pytest tests/` instead.

**Comment by marco-c** [comment]
All right, let's do that, should be trivial.
